-- ============================================================
-- BME – Modelo de Usuário, Perfil e Privilégio
-- Banco: Oracle · Flyway migration V1
-- ============================================================

-- Sequences
CREATE SEQUENCE SEQ_BME_PRIVILEGE  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BME_RESEARCH   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BME_PROFILE    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BME_USER       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ──────────────────────────────────────────────
-- PRIVILEGE – capacidades funcionais
-- ──────────────────────────────────────────────
CREATE TABLE BME_PRIVILEGE (
    ID              NUMBER          NOT NULL,
    CODE            VARCHAR2(60)    NOT NULL,   -- ex: QUERY_EXECUTE, EXPORT_CSV
    DESCRIPTION     VARCHAR2(200)   NOT NULL,
    RESOURCE_TYPE   VARCHAR2(20)    NOT NULL,   -- FEATURE | RESEARCH
    CONSTRAINT PK_PRIVILEGE     PRIMARY KEY (ID),
    CONSTRAINT UK_PRIVILEGE_CODE UNIQUE (CODE)
);

-- ──────────────────────────────────────────────
-- RESEARCH – pesquisas do IBGE disponíveis no BME
-- ──────────────────────────────────────────────
CREATE TABLE BME_RESEARCH (
    ID          NUMBER          NOT NULL,
    CODE        VARCHAR2(30)    NOT NULL,   -- ex: CD2010, PNAD2022
    NAME        VARCHAR2(200)   NOT NULL,
    DESCRIPTION VARCHAR2(2000),
    ACTIVE      CHAR(1)         DEFAULT 'S' NOT NULL CHECK (ACTIVE IN ('S','N')),
    CONSTRAINT PK_RESEARCH      PRIMARY KEY (ID),
    CONSTRAINT UK_RESEARCH_CODE UNIQUE (CODE)
);

-- ──────────────────────────────────────────────
-- PROFILE – perfis de acesso
-- ──────────────────────────────────────────────
CREATE TABLE BME_PROFILE (
    ID              NUMBER          NOT NULL,
    CODE            VARCHAR2(30)    NOT NULL,   -- PUBLIC | RESEARCHER | ADMIN
    NAME            VARCHAR2(100)   NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    RESEARCHER_UI   CHAR(1)         DEFAULT 'N' NOT NULL CHECK (RESEARCHER_UI IN ('S','N')),
    ACTIVE          CHAR(1)         DEFAULT 'S' NOT NULL CHECK (ACTIVE IN ('S','N')),
    CONSTRAINT PK_PROFILE      PRIMARY KEY (ID),
    CONSTRAINT UK_PROFILE_CODE UNIQUE (CODE)
);

-- ──────────────────────────────────────────────
-- PROFILE × PRIVILEGE (N:N)
-- ──────────────────────────────────────────────
CREATE TABLE BME_PROFILE_PRIVILEGE (
    PROFILE_ID      NUMBER  NOT NULL,
    PRIVILEGE_ID    NUMBER  NOT NULL,
    CONSTRAINT PK_PROFILE_PRIVILEGE PRIMARY KEY (PROFILE_ID, PRIVILEGE_ID),
    CONSTRAINT FK_PP_PROFILE   FOREIGN KEY (PROFILE_ID)   REFERENCES BME_PROFILE  (ID),
    CONSTRAINT FK_PP_PRIVILEGE FOREIGN KEY (PRIVILEGE_ID) REFERENCES BME_PRIVILEGE (ID)
);

-- ──────────────────────────────────────────────
-- PROFILE × RESEARCH (N:N com nível de acesso)
-- ──────────────────────────────────────────────
CREATE TABLE BME_PROFILE_RESEARCH (
    PROFILE_ID      NUMBER      NOT NULL,
    RESEARCH_ID     NUMBER      NOT NULL,
    ACCESS_LEVEL    VARCHAR2(10) NOT NULL CHECK (ACCESS_LEVEL IN ('READ','EXPORT','MANAGE')),
    CONSTRAINT PK_PROFILE_RESEARCH  PRIMARY KEY (PROFILE_ID, RESEARCH_ID),
    CONSTRAINT UK_PROFILE_RESEARCH  UNIQUE (PROFILE_ID, RESEARCH_ID),
    CONSTRAINT FK_PR_PROFILE        FOREIGN KEY (PROFILE_ID)  REFERENCES BME_PROFILE  (ID),
    CONSTRAINT FK_PR_RESEARCH       FOREIGN KEY (RESEARCH_ID) REFERENCES BME_RESEARCH (ID)
);

-- ──────────────────────────────────────────────
-- USER – usuários do BME
-- ──────────────────────────────────────────────
CREATE TABLE BME_USER (
    ID              NUMBER          NOT NULL,
    USERNAME        VARCHAR2(100)   NOT NULL,
    FULL_NAME       VARCHAR2(200)   NOT NULL,
    EMAIL           VARCHAR2(200)   NOT NULL,
    AUTH_TYPE       VARCHAR2(10)    NOT NULL CHECK (AUTH_TYPE IN ('AD','GOVBR','BME')),
    EXTERNAL_ID     VARCHAR2(100),              -- AD guid ou gov.br sub
    PASSWORD_HASH   VARCHAR2(72),               -- bcrypt; NULL para AD/GOVBR
    PROFILE_ID      NUMBER          NOT NULL,
    ACTIVE          CHAR(1)         DEFAULT 'S' NOT NULL CHECK (ACTIVE IN ('S','N')),
    CREATED_AT      DATE            DEFAULT SYSDATE NOT NULL,
    LAST_LOGIN      DATE,
    FAILED_LOGINS   NUMBER          DEFAULT 0 NOT NULL,
    LOCKED_UNTIL    DATE,
    CONSTRAINT PK_USER              PRIMARY KEY (ID),
    CONSTRAINT UK_USER_USERNAME     UNIQUE (USERNAME),
    CONSTRAINT UK_USER_EMAIL        UNIQUE (EMAIL),
    CONSTRAINT UK_USER_EXTERNAL_ID  UNIQUE (AUTH_TYPE, EXTERNAL_ID),
    CONSTRAINT FK_USER_PROFILE      FOREIGN KEY (PROFILE_ID) REFERENCES BME_PROFILE (ID),
    -- senha obrigatória apenas para conta local
    CONSTRAINT CK_USER_BME_PASSWORD CHECK (
        AUTH_TYPE != 'BME' OR PASSWORD_HASH IS NOT NULL
    )
);

-- Índices de busca frequente
CREATE INDEX IDX_USER_PROFILE    ON BME_USER (PROFILE_ID);
CREATE INDEX IDX_USER_AUTH_TYPE  ON BME_USER (AUTH_TYPE);
CREATE INDEX IDX_USER_ACTIVE     ON BME_USER (ACTIVE);

-- ──────────────────────────────────────────────
-- DADOS INICIAIS
-- ──────────────────────────────────────────────

-- Privilégios
INSERT INTO BME_PRIVILEGE (ID, CODE, DESCRIPTION, RESOURCE_TYPE) VALUES
    (SEQ_BME_PRIVILEGE.NEXTVAL, 'QUERY_EXECUTE',           'Executar consultas agregadas',            'FEATURE');
INSERT INTO BME_PRIVILEGE (ID, CODE, DESCRIPTION, RESOURCE_TYPE) VALUES
    (SEQ_BME_PRIVILEGE.NEXTVAL, 'EXPORT_CSV',              'Exportar resultados em CSV',              'FEATURE');
INSERT INTO BME_PRIVILEGE (ID, CODE, DESCRIPTION, RESOURCE_TYPE) VALUES
    (SEQ_BME_PRIVILEGE.NEXTVAL, 'EXPORT_XLSX',             'Exportar resultados em XLSX',             'FEATURE');
INSERT INTO BME_PRIVILEGE (ID, CODE, DESCRIPTION, RESOURCE_TYPE) VALUES
    (SEQ_BME_PRIVILEGE.NEXTVAL, 'EXPORT_JSON',             'Exportar resultados em JSON',             'FEATURE');
INSERT INTO BME_PRIVILEGE (ID, CODE, DESCRIPTION, RESOURCE_TYPE) VALUES
    (SEQ_BME_PRIVILEGE.NEXTVAL, 'QUERY_SAVE',              'Salvar consultas pessoais',               'FEATURE');
INSERT INTO BME_PRIVILEGE (ID, CODE, DESCRIPTION, RESOURCE_TYPE) VALUES
    (SEQ_BME_PRIVILEGE.NEXTVAL, 'QUERY_SHARE',             'Compartilhar consultas',                  'FEATURE');
INSERT INTO BME_PRIVILEGE (ID, CODE, DESCRIPTION, RESOURCE_TYPE) VALUES
    (SEQ_BME_PRIVILEGE.NEXTVAL, 'OFFICIAL_QUERY_MANAGE',   'Gerenciar consultas oficiais IBGE',       'FEATURE');
INSERT INTO BME_PRIVILEGE (ID, CODE, DESCRIPTION, RESOURCE_TYPE) VALUES
    (SEQ_BME_PRIVILEGE.NEXTVAL, 'RESEARCHER_UI',           'Acesso à interface avançada de pesquisa', 'FEATURE');
INSERT INTO BME_PRIVILEGE (ID, CODE, DESCRIPTION, RESOURCE_TYPE) VALUES
    (SEQ_BME_PRIVILEGE.NEXTVAL, 'ADMIN_USERS',             'Gestão de usuários e perfis',             'FEATURE');
INSERT INTO BME_PRIVILEGE (ID, CODE, DESCRIPTION, RESOURCE_TYPE) VALUES
    (SEQ_BME_PRIVILEGE.NEXTVAL, 'ADMIN_RESEARCH',          'Gestão de pesquisas e variáveis',         'FEATURE');

-- Pesquisas
INSERT INTO BME_RESEARCH (ID, CODE, NAME, ACTIVE) VALUES (SEQ_BME_RESEARCH.NEXTVAL, 'CD2010', 'Censo Demográfico 2010', 'S');
INSERT INTO BME_RESEARCH (ID, CODE, NAME, ACTIVE) VALUES (SEQ_BME_RESEARCH.NEXTVAL, 'CD2022', 'Censo Demográfico 2022', 'S');
INSERT INTO BME_RESEARCH (ID, CODE, NAME, ACTIVE) VALUES (SEQ_BME_RESEARCH.NEXTVAL, 'PNAD',   'PNAD Contínua',          'S');
INSERT INTO BME_RESEARCH (ID, CODE, NAME, ACTIVE) VALUES (SEQ_BME_RESEARCH.NEXTVAL, 'POF',    'POF 2017-18',            'S');
INSERT INTO BME_RESEARCH (ID, CODE, NAME, ACTIVE) VALUES (SEQ_BME_RESEARCH.NEXTVAL, 'AMS',    'AMS',                    'S');
INSERT INTO BME_RESEARCH (ID, CODE, NAME, ACTIVE) VALUES (SEQ_BME_RESEARCH.NEXTVAL, 'MUNIC',  'MUNIC',                  'S');
INSERT INTO BME_RESEARCH (ID, CODE, NAME, ACTIVE) VALUES (SEQ_BME_RESEARCH.NEXTVAL, 'PNSB',   'PNSB',                   'S');

-- Perfis
INSERT INTO BME_PROFILE (ID, CODE, NAME, DESCRIPTION, RESEARCHER_UI, ACTIVE) VALUES
    (SEQ_BME_PROFILE.NEXTVAL, 'PUBLIC',
     'Público geral', 'Acesso às pesquisas abertas e consultas oficiais', 'N', 'S');
INSERT INTO BME_PROFILE (ID, CODE, NAME, DESCRIPTION, RESEARCHER_UI, ACTIVE) VALUES
    (SEQ_BME_PROFILE.NEXTVAL, 'RESEARCHER',
     'Pesquisador', 'Interface avançada, exportação e pesquisas restritas', 'S', 'S');
INSERT INTO BME_PROFILE (ID, CODE, NAME, DESCRIPTION, RESEARCHER_UI, ACTIVE) VALUES
    (SEQ_BME_PROFILE.NEXTVAL, 'ADMIN',
     'Administrador', 'Gestão completa de usuários, perfis e conteúdo', 'S', 'S');

-- Privilégios do perfil PUBLIC
INSERT INTO BME_PROFILE_PRIVILEGE (PROFILE_ID, PRIVILEGE_ID)
    SELECT p.ID, pr.ID FROM BME_PROFILE p, BME_PRIVILEGE pr
    WHERE p.CODE = 'PUBLIC' AND pr.CODE IN ('QUERY_EXECUTE', 'QUERY_SAVE');

-- Privilégios do perfil RESEARCHER
INSERT INTO BME_PROFILE_PRIVILEGE (PROFILE_ID, PRIVILEGE_ID)
    SELECT p.ID, pr.ID FROM BME_PROFILE p, BME_PRIVILEGE pr
    WHERE p.CODE = 'RESEARCHER'
    AND pr.CODE IN ('QUERY_EXECUTE','EXPORT_CSV','EXPORT_XLSX','EXPORT_JSON',
                    'QUERY_SAVE','QUERY_SHARE','RESEARCHER_UI');

-- Privilégios do perfil ADMIN
INSERT INTO BME_PROFILE_PRIVILEGE (PROFILE_ID, PRIVILEGE_ID)
    SELECT p.ID, pr.ID FROM BME_PROFILE p, BME_PRIVILEGE pr
    WHERE p.CODE = 'ADMIN';  -- todos os privilégios

-- Acesso às pesquisas por perfil
-- PUBLIC: apenas pesquisas abertas (CD2010, CD2022, PNAD) com READ
INSERT INTO BME_PROFILE_RESEARCH (PROFILE_ID, RESEARCH_ID, ACCESS_LEVEL)
    SELECT p.ID, r.ID, 'READ'
    FROM BME_PROFILE p, BME_RESEARCH r
    WHERE p.CODE = 'PUBLIC' AND r.CODE IN ('CD2010','CD2022','PNAD');

-- RESEARCHER: todas as pesquisas com EXPORT
INSERT INTO BME_PROFILE_RESEARCH (PROFILE_ID, RESEARCH_ID, ACCESS_LEVEL)
    SELECT p.ID, r.ID, 'EXPORT'
    FROM BME_PROFILE p, BME_RESEARCH r
    WHERE p.CODE = 'RESEARCHER';

-- ADMIN: todas as pesquisas com MANAGE
INSERT INTO BME_PROFILE_RESEARCH (PROFILE_ID, RESEARCH_ID, ACCESS_LEVEL)
    SELECT p.ID, r.ID, 'MANAGE'
    FROM BME_PROFILE p, BME_RESEARCH r
    WHERE p.CODE = 'ADMIN';

COMMIT;
